# Generated by Django 4.1.3 on 2022-12-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='started_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='up_to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
