# Generated by Django 4.1.3 on 2023-01-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='_', max_length=1500)),
                ('date', models.DateField(blank=True, null=True)),
                ('done', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
