# Generated by Django 4.1.3 on 2023-01-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.TextField(default='_', max_length=1500)),
                ('content', models.TextField(default='_', max_length=1500)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='identifier',
            field=models.TextField(default='_', max_length=50),
        ),
    ]
