# Generated by Django 4.1.3 on 2023-01-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_notification_identifier_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='file',
            field=models.TextField(default='_', max_length=1500),
        ),
    ]
